server:
  port: 8098

spring:
  application:
    name: batch-v5
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  datasource:
    url: jdbc:postgresql://localhost:5433/demo
    username: postgres_user
    password: postgres_pwd
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://mongo_user:mongo_pwd@localhost:27017/demo?authSource=admin
      username: mongo_user
      password: mongo_pwd
      auto-index-creation: false
      database: demo

